export { Capicola } from "./capicola"
export type {
  CapicolaProps,
  CaptionTheme,
  CaptionPreset,
  CaptionPlacement,
  CaptionMode,
  Quote,
  QuoteOptions,
  CaptionData,
  WordTiming,
  CadenceOptions,
  AnchorX,
  AnchorY,
  ChunkingOptions,
  CaptionWidth,
  CaptionAlign,
  UseAudioWordSyncArgs,
  UseAudioWordSyncResult,
} from "./types"
